# Generated by Django 4.2.16 on 2024-10-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
