# Generated by Django 4.2.16 on 2024-10-18 02:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'crop': True, 'height': 100, 'width': 100}}),
        ),
    ]
